name: Python CI

on:
  push:
    branches:
      - main          # Runs on push to 'main' branch
  pull_request:
    branches:
      - main          # Runs on pull requests to 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest   # Use the latest Ubuntu environment for CI

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2   # Checkout the code in your repository

    - name: Set up Python 3.13
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'   # Using Python 3.13 for the CI environment

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install -r requirements.txt    # Install any dependencies listed in requirements.txt

    - name: Run tests with unittest
      run: |
        python -m unittest discover -s tests -v -f # Run tests

